### ISSUE TITLE
회원가입 기능 구현

### ISSUE THREAD

**Issue by cndqjacndqja** [Billage-woowacourse/Billage#1]
페어로 기능 구현

**Comment by sojukang** [comment]
H2 DB 예약어로 `user` 가 등록되어 있어서 JPA로 생성하려고 할 때 에러가 떴네요~ `User` -> `Member`로 수정했습니다.

**Comment by sojukang** [comment]
[PR 링크](https://github.com/Billage-woowacourse/Billage/pull/4)
회원 가입 기능 구현 PR입니다.

**Comment by sojukang** [comment]
@cndqjacndqja  [PR 링크](https://github.com/Billage-woowacourse/Billage/pull/4)
피드백 반영(기본 생성자) PR입니다.

**Comment by cndqjacndqja** [comment]
크 깃똥찬 소주캉 👍
